spring.application.name=collection-service
springdoc.swagger-ui.url=/openapi.yaml
springdoc.swagger-ui.disable-swagger-default-url=true
server.port=${PORT:8081}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/space_marine}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}
spring.flyway.schemas=collection
spring.flyway.default-schema=collection
spring.datasource.hikari.connection-init-sql=SET search_path TO collection
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=collection
spring.jpa.open-in-view=false
spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.default-property-inclusion=always
openapi.spaceMarineCollection.base-path=/api/v1
collection.base-url=${COLLECTION_URL:http://localhost:8081/api/v1}
